<style type="text/css">
    table.gridtable {
        font-family: verdana,arial,sans-serif;
        font-size:11px;
        color:#333333;
        border-width: 1px;
        border-color: #666666;
        border-collapse: collapse;
    }
    table.gridtable th {
        border-width: 1px;
        padding: 8px;
        border-style: solid;
        border-color: #666666;
        background-color: #dedede;
    }
    table.gridtable td {
        border-width: 1px;
        padding: 8px;
        border-style: solid;
        border-color: #666666;
        background-color: #ffffff;
    }
</style>
<table class="gridtable">
    <tr>
        <th>Name</th>
        <th>Contact No</th>
        <th>Address</th>
        <th>Website</th>
    </tr>
    <?php
    $collection=$this->getCollection();

    foreach($collection as $each){?>

        <tr>
            <td><?php echo $each->getData()['name'] ?></td>
            <td><?php echo $each->getData()['phone'] ?></td>
            <td><?php echo $each->getData()['address'] ?></td>
            <td>
                <?php
                echo  $this->getStoreName($each->getData()['store_id']);

                ?>
            </td>
        </tr>
        <?php

    }
    ?>
    <!-- CSS goes in the document HEAD or added to your external stylesheet -->

    <!-- Table goes in the document BODY -->

</table>
